name: Keep Render Alive

on:
  schedule:
    # 7:30 AM - 11:25 PM IST
    - cron: "*/5 2-17 * * *"

    # 11:30 PM IST
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping APIs
        run: |
          curl --fail --show-error --silent \
            https://quotify-i62o.onrender.com/api/v1/ping

          curl --fail --show-error --silent \
            https://quotify-t879.onrender.com/api/v1/ping
